### PR TITLE
Fix issue #21

### PR DESCRIPTION
**Pull request by RusTit**
Thanks to @gregbacchus
https://github.com/atlassian/koa-oas3/issues/21#issue-517452237

### CODE REVIEW

**Comment by supertong** [comment]
Thanks! LGTM. Would you be able to generate a changeset by running `yarn changeset` command?
https://github.com/atlassian/changesets/blob/master/packages/cli/README.md

**Comment by RusTit** [comment]
@supertong Yes, I'm checked your command (never use that package before) and got a bit confused.
What answers should I give this tool in order to form the list of changes in the best way?
I've tried this:
```
titan@dvkam-w-srto241> yarn changeset                                                                                                                                                                                                               ~/code/nodejs/koa-oas3
yarn run v1.21.1
$ /home/titan/code/nodejs/koa-oas3/node_modules/.bin/changeset
🦋  Which packages should have a major bump? · No items were selected
🦋  Which packages should have a minor bump? · No items were selected
🦋  The following packages will be patch bumped:
🦋  koa-oas3@0.15.0
🦋  Please enter a summary for this change (this will be in the changelogs)
🦋  Summary · Fix issue #21
🦋  === Releasing the following packages ===
🦋  [Patch]
🦋    koa-oas3
🦋  ╔╗
🦋  ║ ========= NOTE ========   ║
🦋  ║All dependents of these packages that will be incompatible with the new version will be patch bumped when this changeset is applied.║
🦋  ╚╝
🦋  Is this your desired changeset? (Y/n) · true
🦋  Changeset added! - you can now commit it
🦋  
🦋  If you want to modify or expand on the changeset summary, you can find it here
🦋  info /home/titan/code/nodejs/koa-oas3/.changeset/tricky-crabs-peel.md
Done in 16.37s.
titan@dvkam-w-srto241>       
```
and result was new folder `.changeset` with files.
![изображение](https://user-images.githubusercontent.com/29846693/71215990-e8280680-2304-11ea-9f32-def8f1620496.png)
Should I add those files with commit?

**Comment by supertong** [comment]
Hey @RusTit , yes, please commit the .changeset folder.

**Comment by RusTit** [comment]
@supertong Done.

**Pull request merged**
