### PR TITLE
Fix path params

### PR DESCRIPTION
**Pull request by crizo23**
Because the validated request (done by oas3-chow-chow) doesn't set `validRequest.path.params`, this line was resulting in `ctx.oas.request.params` to always be undefined
          `params: validRequest.path && validRequest.path.params,`

removing `&& validRequest.path.params` fixes this.

### CODE REVIEW

**Comment by crizo23** [comment]
@supertong hello - just following up on this. Do you know when you might have time to catch up on PRs?

**Comment by supertong** [comment]
Thanks @crizo23 , left a nit comment otherwise it looks good to me.

**Comment by crizo23** [comment]
@supertong sorry, I don't see a comment?

**Comment by supertong** [comment]
@crizo23 , it's ok and it was just a nit change. I will merge in your change.

**Pull request merged**
