### PR TITLE
Update oas3-chow-chow to version 1.1.3

### PR DESCRIPTION
**Pull request by crizo23**

### CODE REVIEW

**Comment by crizo23** [comment]
@supertong For some reason I can't add you as a PR reviewer?

**Comment by crizo23** [comment]
@supertong not sure what to do about this Travis CI error:
`error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.`

**Review by supertong — COMMENTED** [review]
Thanks for the contribution @crizo23 . I think you forgot to commit the yarn lock file and that's why the build is complaining.

**Comment by crizo23** [comment]
> Thanks for the contribution @crizo23 . I think you forgot to commit the yarn lock file and that's why the build is complaining.

@supertong Thanks, I forgot to run yarn. I just checked it in.

**Pull request merged**
